name: my-laravel-app

services:
  - name: web
    github:
      repo: TU_USUARIO/TU_REPOSITORIO
      branch: main
    build_command: |
      composer install --no-interaction --prefer-dist --optimize-autoloader
      php artisan optimize

