name: my-laravel-app

services:
  - name: web
    github:
      repo: Xeexen/practice-project
      branch: main
    build_command: |
      composer install --no-interaction --prefer-dist --optimize-autoloader
      php artisan optimize
    run_command: php artisan serve --host=0.0.0.0 --port=8080
    http_port: 8080
    envs:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
